# Generated by Django 4.2 on 2023-06-04 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dia_2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peopleinfo',
            old_name='bp',
            new_name='HbA1c_level',
        ),
        migrations.RenameField(
            model_name='peopleinfo',
            old_name='dpf',
            new_name='blood_glucose_level',
        ),
        migrations.RenameField(
            model_name='peopleinfo',
            old_name='glu',
            new_name='heart_disease',
        ),
        migrations.RenameField(
            model_name='peopleinfo',
            old_name='insulin',
            new_name='hypertension',
        ),
        migrations.RenameField(
            model_name='peopleinfo',
            old_name='preg',
            new_name='smoking_history',
        ),
        migrations.RemoveField(
            model_name='peopleinfo',
            name='name',
        ),
    ]
